### ISSUE TITLE
Response processing is completely broken

### ISSUE THREAD

**Issue by stacksmith** [JadedCtrl/cl-ipfs-api2#3]
Responses from the API are truncated.  Only the first response is processed; however, many API calls return long sequences of responses.  YASON:PARSE must be fed a stream, parsing as many items as there are in the stream (it is currently fed a string, and it gives up after the first item).

Please refer to the previous issues I opened for a possible solution.

As it stands the library is largely broken.

**Comment by JadedCtrl** [comment]
Sorry about the bitrot, and thanks for the reports!
I'll try and get them fixed within the next couple days.

**Comment by JadedCtrl** [comment]
I made the changes you suggested, along with a few other simplifications-- everything should be working just fine now, give it another go. Thanks for the detailed reports. :)

**Comment by stacksmith** [comment]
No, thank you - for fixing things quickly and sharing the library in the first place.  I was beginning to feel like a total nuisance!
I will give your changes a try.

**Comment by stacksmith** [comment]
Seems to work.
